package com.applause.cloudsource.app.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.applause.cloudsource.app.persistent.Device;
import com.applause.cloudsource.app.persistent.Tester;

/**
 * Class _Bug was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Bug extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String DEVICE_ID_PK_COLUMN = "deviceId";
    public static final String ID_PK_COLUMN = "id";
    public static final String TESTER_ID_PK_COLUMN = "testerId";

    public static final Property<String> BUG_ID = Property.create("bugId", String.class);
    public static final Property<Device> DEVICE = Property.create("device", Device.class);
    public static final Property<Tester> TESTER = Property.create("tester", Tester.class);

    public void setBugId(String bugId) {
        writeProperty("bugId", bugId);
    }
    public String getBugId() {
        return (String)readProperty("bugId");
    }

    public void setDevice(Device device) {
        setToOneTarget("device", device, true);
    }

    public Device getDevice() {
        return (Device)readProperty("device");
    }


    public void setTester(Tester tester) {
        setToOneTarget("tester", tester, true);
    }

    public Tester getTester() {
        return (Tester)readProperty("tester");
    }


}
