package com.applause.cloudsource.app.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.applause.cloudsource.app.persistent.TesterDevice;

/**
 * Class _Device was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Device extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> DESCRIPTION = Property.create("description", String.class);
    public static final Property<String> DEVICE_ID = Property.create("deviceId", String.class);
    public static final Property<List<TesterDevice>> TESTERS = Property.create("testers", List.class);

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }

    public void setDeviceId(String deviceId) {
        writeProperty("deviceId", deviceId);
    }
    public String getDeviceId() {
        return (String)readProperty("deviceId");
    }

    public void addToTesters(TesterDevice obj) {
        addToManyTarget("testers", obj, true);
    }
    public void removeFromTesters(TesterDevice obj) {
        removeToManyTarget("testers", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<TesterDevice> getTesters() {
        return (List<TesterDevice>)readProperty("testers");
    }


}
