package com.applause.cloudsource.app.persistent.auto;

import java.time.LocalDate;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.applause.cloudsource.app.persistent.TesterDevice;

/**
 * Class _Tester was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Tester extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> COUNTRY = Property.create("country", String.class);
    public static final Property<String> FIRST_NAME = Property.create("firstName", String.class);
    public static final Property<LocalDate> LAST_LOGIN = Property.create("lastLogin", LocalDate.class);
    public static final Property<String> LAST_NAME = Property.create("lastName", String.class);
    public static final Property<String> TESTER_ID = Property.create("testerId", String.class);
    public static final Property<List<TesterDevice>> DEVICES = Property.create("devices", List.class);

    public void setCountry(String country) {
        writeProperty("country", country);
    }
    public String getCountry() {
        return (String)readProperty("country");
    }

    public void setFirstName(String firstName) {
        writeProperty("firstName", firstName);
    }
    public String getFirstName() {
        return (String)readProperty("firstName");
    }

    public void setLastLogin(LocalDate lastLogin) {
        writeProperty("lastLogin", lastLogin);
    }
    public LocalDate getLastLogin() {
        return (LocalDate)readProperty("lastLogin");
    }

    public void setLastName(String lastName) {
        writeProperty("lastName", lastName);
    }
    public String getLastName() {
        return (String)readProperty("lastName");
    }

    public void setTesterId(String testerId) {
        writeProperty("testerId", testerId);
    }
    public String getTesterId() {
        return (String)readProperty("testerId");
    }

    public void addToDevices(TesterDevice obj) {
        addToManyTarget("devices", obj, true);
    }
    public void removeFromDevices(TesterDevice obj) {
        removeToManyTarget("devices", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<TesterDevice> getDevices() {
        return (List<TesterDevice>)readProperty("devices");
    }


}
